name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [14, 16, 17]
    steps:
      # Get BuildTools from https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: "Getting BuildTools"
        run: "curl https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -o ./BuildTools.jar"

      - name: "Set up JDK 14"
        uses: "actions/setup-java@v3"
        with:
          distribution: "zulu"
          java-version: "14"

      # Build Spigot by BuildTools
      - name: "Building Spigot 1.15.2"
        run: "java -jar BuildTools.jar --rev 1.15.2"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{matrix.java-version}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'zulu'
          cache: 'gradle'
          architecture: x64
      - name: Grant permissions for gradlew
        run: chmod +x ./gradlew
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info